# Generated by Django 5.1.2 on 2025-12-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0005_remove_profile_address_remove_profile_salario_and_more"),
        ("iotApp", "0001_initial"),
        ("sucursalApp", "0033_nozzle_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispenseevent",
            name="firefighter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispense_events",
                to="UsuarioApp.profile",
            ),
        ),
        migrations.AddField(
            model_name="dispenseevent",
            name="fuel_numeral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispense_events",
                to="sucursalApp.machinefuelinventorynumeral",
            ),
        ),
        migrations.AddField(
            model_name="dispenseevent",
            name="nozzle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispense_events",
                to="sucursalApp.nozzle",
            ),
        ),
        migrations.AddField(
            model_name="dispenseevent",
            name="service_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispense_events",
                to="sucursalApp.servicesession",
            ),
        ),
    ]
