# Generated by Django 5.1.2 on 2025-12-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iotApp",
            "0002_dispenseevent_firefighter_dispenseevent_fuel_numeral_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispenseevent",
            name="pistola",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
