# Generated by Django 5.1.2 on 2025-09-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="contrato",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/contratos/",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_hire",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de contratación"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="examen_medico",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/examenes/",
                verbose_name="Examen médico",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_partime",
            field=models.BooleanField(
                choices=[(True, "Tiempo completo"), (False, "Medio tiempo")],
                default=False,
                verbose_name="Tipo de jornada",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="salario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Salario",
            ),
        ),
    ]
