# Generated by Django 5.1.2 on 2025-11-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="permission_code",
            field=models.CharField(
                choices=[
                    ("OWNER", "Dueño"),
                    ("ADMINISTRATOR", "Administrador"),
                    ("ACCOUNTANT", "Secretario(a)"),
                    ("HEAD_ATTENDANT", "Bombero encargado"),
                    ("ATTENDANT", "Bombero"),
                ],
                default="ATTENDANT",
                max_length=25,
            ),
        ),
    ]
