# Generated by Django 5.1.2 on 2025-09-15 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_profile_address_profile_contrato_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=1,
                null=True,
                verbose_name="Sexo",
            ),
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asistencia",
                    models.PositiveIntegerField(default=0, verbose_name="Asistencia"),
                ),
                (
                    "vacaciones",
                    models.PositiveIntegerField(default=0, verbose_name="Vacaciones"),
                ),
                (
                    "permisos",
                    models.PositiveIntegerField(default=0, verbose_name="Permisos"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "statistics",
            },
        ),
    ]
