# Generated by Django 5.1.2 on 2025-12-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0003_alter_position_permission_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rut",
            field=models.CharField(
                blank=True,
                help_text="RUT sin puntos, con guión opcional. Ej: 12345678-5",
                max_length=12,
                null=True,
                unique=True,
                verbose_name="RUT",
            ),
        ),
    ]
