# Generated by Django 5.1.2 on 2025-09-20 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0004_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company_rut",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un RUT válido en el formato 12.345.678-9",
                        regex="^[0-9.]+-[0-9kK]{1}$",
                    )
                ],
                verbose_name="RUT Empresa",
            ),
        ),
    ]
