# Generated by Django 5.1.2 on 2025-12-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0004_profile_rut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="salario",
        ),
        migrations.AddField(
            model_name="profile",
            name="codigo_identificador",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Código identificador",
            ),
        ),
    ]
