# Generated by Django 5.1.2 on 2025-12-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0005_remove_profile_address_remove_profile_salario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
