# Generated by Django 5.1.2 on 2025-09-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0005_profile_company_rut"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
