# Generated by Django 5.1.2 on 2025-09-21 03:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("UsuarioApp", "0006_delete_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ingrese un RUT válido en el formato 12.345.678-9",
                                regex="^[0-9.]+-[0-9kK]{1}$",
                            )
                        ],
                        verbose_name="RUT",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=255, verbose_name="Razón social"),
                ),
                (
                    "tax_address",
                    models.CharField(
                        max_length=255, verbose_name="Dirección tributaria"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="UsuarioApp.profile",
                        verbose_name="Perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "UsuarioApp_company",
            },
        ),
    ]
