# Generated by Django 5.1.2 on 2025-09-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sucursal",
            name="users",
        ),
        migrations.CreateModel(
            name="Island",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_islands",
                        to="sucursalApp.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Isla",
                "verbose_name_plural": "Islas",
                "ordering": ("number",),
                "unique_together": {("sucursal", "number")},
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "initial_numeral",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Numeral inicial",
                    ),
                ),
                (
                    "final_numeral",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Numeral final",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo de combustible"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="sucursalApp.island",
                        verbose_name="Isla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Máquina",
                "verbose_name_plural": "Máquinas",
                "ordering": ("number",),
                "unique_together": {("island", "number")},
            },
        ),
        migrations.CreateModel(
            name="Nozzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "initial_numeral",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Numeral inicial",
                    ),
                ),
                (
                    "final_numeral",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Numeral final",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo de combustible"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nozzles",
                        to="sucursalApp.machine",
                        verbose_name="Máquina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pistola",
                "verbose_name_plural": "Pistolas",
                "ordering": ("number",),
                "unique_together": {("machine", "number")},
            },
        ),
        migrations.CreateModel(
            name="SucursalStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OWNER", "Dueño"),
                            ("ADMINISTRATOR", "Administrador"),
                            ("ACCOUNTANT", "Contador"),
                            ("HEAD_ATTENDANT", "Bombero encargado"),
                            ("ATTENDANT", "Bombero"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Rol",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursal_staff",
                        to="UsuarioApp.profile",
                        verbose_name="Perfil",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="sucursalApp.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal de sucursal",
                "verbose_name_plural": "Personal de sucursal",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sucursal", "profile"), name="unique_sucursal_profile"
                    )
                ],
            },
        ),
    ]
