# Generated by Django 5.1.2 on 2025-09-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0003_shift_shiftassignment_shiftschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="sucursal",
        ),
        migrations.RemoveField(
            model_name="shiftassignment",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="shiftassignment",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="shiftassignment",
            name="sucursal",
        ),
        migrations.DeleteModel(
            name="ShiftSchedule",
        ),
        migrations.DeleteModel(
            name="Shift",
        ),
        migrations.DeleteModel(
            name="ShiftAssignment",
        ),
    ]
