# Generated by Django 5.1.2 on 2025-09-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sucursalApp",
            "0004_remove_shift_sucursal_remove_shiftassignment_shift_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nozzle",
            name="final_numeral",
        ),
        migrations.RemoveField(
            model_name="nozzle",
            name="initial_numeral",
        ),
    ]
