# Generated by Django 5.1.2 on 2025-10-14 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0005_remove_nozzle_final_numeral_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=25, verbose_name="Código")),
                ("start_time", models.TimeField(verbose_name="Hora de inicio")),
                ("end_time", models.TimeField(verbose_name="Hora de término")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_shifts",
                        to="UsuarioApp.profile",
                        verbose_name="Encargado del turno",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="sucursalApp.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "ordering": ("sucursal__name", "start_time"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sucursal", "code"), name="unique_sucursal_shift_code"
                    )
                ],
            },
        ),
    ]
