# Generated by Django 5.1.2 on 2025-10-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0006_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Resume las funciones principales y responsabilidades del turno.",
                max_length=255,
                verbose_name="Descripción",
            ),
        ),
    ]
