# Generated by Django 5.1.2 on 2025-10-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0007_shift_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, verbose_name="Código")),
                (
                    "fuel_type",
                    models.CharField(
                        max_length=100, verbose_name="Tipo de combustible"
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Capacidad del tanque (L)",
                    ),
                ),
                (
                    "liters",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Litraje disponible (L)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_inventories",
                        to="sucursalApp.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario de combustible",
                "verbose_name_plural": "Inventarios de combustible",
                "ordering": ("code",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sucursal", "code"),
                        name="unique_inventory_code_per_branch",
                    )
                ],
            },
        ),
    ]
