# Generated by Django 5.1.2 on 2025-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0008_fuelinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="attendants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selecciona los bomberos que trabajarán en este turno.",
                related_name="assigned_shifts",
                to="UsuarioApp.profile",
                verbose_name="Bomberos asignados",
            ),
        ),
    ]
