# Generated by Django 5.1.2 on 2025-10-23 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0009_shift_attendants"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_type", models.CharField(max_length=150, verbose_name="Tipo")),
                ("quantity", models.PositiveIntegerField(verbose_name="Cantidad")),
                ("arrival_date", models.DateField(verbose_name="Fecha de llegada")),
                (
                    "batch_number",
                    models.CharField(max_length=100, verbose_name="Número de lote"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="sucursalApp.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto de sucursal",
                "verbose_name_plural": "Productos de sucursal",
                "ordering": ("product_type", "arrival_date"),
            },
        ),
    ]
