# Generated by Django 5.1.2 on 2025-11-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0010_branchproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coins_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Dinero en monedas",
                    ),
                ),
                (
                    "cash_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Dinero en efectivo",
                    ),
                ),
                (
                    "initial_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Presupuesto inicial",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "attendants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_sessions",
                        to="UsuarioApp.profile",
                        verbose_name="Bomberos asignados",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_sessions",
                        to="sucursalApp.shift",
                        verbose_name="Turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inicio de servicio",
                "verbose_name_plural": "Inicios de servicio",
                "ordering": ("-started_at",),
            },
        ),
    ]
