# Generated by Django 5.1.2 on 2025-11-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0011_servicesession"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSessionFuelLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liters_added",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Litros cargados (L)",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=100, verbose_name="Número de factura"),
                ),
                (
                    "driver_name",
                    models.CharField(max_length=150, verbose_name="Nombre del chofer"),
                ),
                (
                    "license_plate",
                    models.CharField(max_length=20, verbose_name="Patente"),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_loads",
                        to="sucursalApp.fuelinventory",
                        verbose_name="Inventario",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_loads",
                        to="UsuarioApp.profile",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "service_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_loads",
                        to="sucursalApp.servicesession",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga de combustible",
                "verbose_name_plural": "Cargas de combustible",
                "ordering": ("-date", "-created_at"),
            },
        ),
    ]
