# Generated by Django 5.1.2 on 2025-11-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0012_servicesessionfuelload"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSessionProductLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_added",
                    models.PositiveIntegerField(verbose_name="Cantidad agregada"),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_loads",
                        to="sucursalApp.branchproduct",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_loads",
                        to="UsuarioApp.profile",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "service_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_loads",
                        to="sucursalApp.servicesession",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso de producto",
                "verbose_name_plural": "Ingresos de productos",
                "ordering": ("-date", "-created_at"),
            },
        ),
    ]
