# Generated by Django 5.1.2 on 2025-11-13 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0013_servicesessionproductload"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSessionProductSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora de venta"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_sales",
                        to="UsuarioApp.profile",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "service_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_sales",
                        to="sucursalApp.servicesession",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta de productos",
                "verbose_name_plural": "Ventas de productos",
                "ordering": ("-sold_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ServiceSessionProductSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Cantidad vendida"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="sucursalApp.branchproduct",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sucursalApp.servicesessionproductsale",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto vendido",
                "verbose_name_plural": "Productos vendidos",
                "ordering": ("product__product_type",),
            },
        ),
    ]
