# Generated by Django 5.1.2 on 2025-11-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0014_servicesessionproductsale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSessionCreditSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=100, verbose_name="Número de factura"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Nombre del cliente"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto del crédito",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "fuel_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_sales",
                        to="sucursalApp.fuelinventory",
                        verbose_name="Estanque",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_sales",
                        to="UsuarioApp.profile",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "service_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_sales",
                        to="sucursalApp.servicesession",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta a crédito",
                "verbose_name_plural": "Ventas a crédito",
                "ordering": ("-created_at", "-pk"),
            },
        ),
    ]
