# Generated by Django 5.1.2 on 2025-11-15 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0015_servicesessioncreditsale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSessionWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto retirado"
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_session_withdrawals",
                        to="UsuarioApp.profile",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "service_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="sucursalApp.servicesession",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tirada de caja",
                "verbose_name_plural": "Tiradas de caja",
                "ordering": ("-registered_at", "-pk"),
            },
        ),
    ]
