# Generated by Django 5.1.2 on 2025-11-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_initial"),
        ("sucursalApp", "0017_servicesessionfirefighterpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSessionTransbankVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_count",
                    models.PositiveIntegerField(verbose_name="Cantidad de vouchers"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto total"
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transbank_vouchers",
                        to="UsuarioApp.profile",
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "service_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transbank_vouchers",
                        to="sucursalApp.servicesession",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher Transbank",
                "verbose_name_plural": "Vouchers Transbank",
                "ordering": ("-registered_at", "-pk"),
            },
        ),
    ]
