# Generated by Django 5.1.2 on 2025-11-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0018_servicesessiontransbankvoucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesession",
            name="ended_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de cierre"
            ),
        ),
    ]
