# Generated by Django 5.1.2 on 2025-11-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0019_servicesession_ended_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="fuel_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="machines",
                to="sucursalApp.fuelinventory",
                verbose_name="Estanque",
            ),
        ),
    ]
