# Generated by Django 5.1.2 on 2025-11-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0020_machine_fuel_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="final_numeral",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="initial_numeral",
        ),
        migrations.AddField(
            model_name="machine",
            name="numeral",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Numeral"
            ),
        ),
    ]
