# Generated by Django 5.1.2 on 2025-11-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0021_remove_machine_final_numeral_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesessionfuelload",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Valor pagado"
            ),
        ),
        migrations.AddField(
            model_name="servicesessionproductload",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Valor pagado"
            ),
        ),
    ]
