# Generated by Django 5.1.2 on 2025-11-26 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0022_servicesessionfuelload_payment_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        max_length=100, verbose_name="Tipo de combustible"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio por litro"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_prices",
                        to="sucursalApp.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de combustible",
                "verbose_name_plural": "Precios de combustible",
                "ordering": ("-created_at", "-pk"),
            },
        ),
    ]
