# Generated by Django 5.1.2 on 2025-11-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0023_fuelprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sucursalstaff",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OWNER", "Dueño"),
                    ("ADMINISTRATOR", "Administrador"),
                    ("ACCOUNTANT", "Secretario(a)"),
                    ("HEAD_ATTENDANT", "Bombero encargado"),
                    ("ATTENDANT", "Bombero"),
                ],
                max_length=25,
                null=True,
                verbose_name="Rol",
            ),
        ),
    ]
