# Generated by Django 5.1.2 on 2025-11-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0024_alter_sucursalstaff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesessioncreditsale",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pendiente"), ("PAID", "Pagado")],
                default="PENDING",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
