# Generated by Django 5.1.2 on 2025-11-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0025_servicesessioncreditsale_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesession",
            name="flow_mismatch_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Monto de descuadre",
            ),
        ),
        migrations.AddField(
            model_name="servicesession",
            name="flow_mismatch_type",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin descuadre"),
                    ("POSITIVE", "Descuadre positivo"),
                    ("NEGATIVE", "Descuadre negativo"),
                ],
                default="NONE",
                max_length=20,
                verbose_name="Tipo de descuadre",
            ),
        ),
    ]
