# Generated by Django 5.1.2 on 2025-11-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0026_servicesession_flow_mismatch_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesessiontransbankvoucher",
            name="voucher_count",
        ),
    ]
