# Generated by Django 5.1.2 on 2025-11-29 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0027_remove_servicesessiontransbankvoucher_voucher_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="fuel_inventories",
            field=models.ManyToManyField(
                blank=True,
                related_name="associated_machines",
                to="sucursalApp.fuelinventory",
                verbose_name="Estanques",
            ),
        ),
        migrations.AddField(
            model_name="nozzle",
            name="fuel_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nozzles",
                to="sucursalApp.fuelinventory",
                verbose_name="Estanque",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="fuel_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="machines",
                to="sucursalApp.fuelinventory",
                verbose_name="Estanque principal",
            ),
        ),
    ]
