# Generated by Django 5.1.2 on 2025-11-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0028_machine_fuel_inventories_nozzle_fuel_inventory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="numeral",
        ),
        migrations.CreateModel(
            name="MachineFuelInventoryNumeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numeral",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Numeral",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "fuel_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine_numerals",
                        to="sucursalApp.fuelinventory",
                        verbose_name="Estanque",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_numerals",
                        to="sucursalApp.machine",
                        verbose_name="Máquina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numeral de máquina",
                "verbose_name_plural": "Numerales de máquina",
                "unique_together": {("machine", "fuel_inventory")},
            },
        ),
    ]
