# Generated by Django 5.1.2 on 2025-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0029_remove_machine_numeral_machinefuelinventorynumeral"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machinefuelinventorynumeral",
            options={
                "ordering": ("machine", "fuel_inventory", "slot", "pk"),
                "verbose_name": "Numeral de máquina",
                "verbose_name_plural": "Numerales de máquina",
            },
        ),
        migrations.AddField(
            model_name="machinefuelinventorynumeral",
            name="slot",
            field=models.PositiveIntegerField(default=1, verbose_name="Posición"),
        ),
    ]
