# Generated by Django 5.1.2 on 2025-12-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0030_alter_machinefuelinventorynumeral_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="machinefuelinventorynumeral",
            unique_together={("machine", "fuel_inventory", "slot")},
        ),
    ]
