# Generated by Django 5.1.2 on 2025-12-09 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0031_alter_machinefuelinventorynumeral_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nozzle",
            name="fuel_inventory",
        ),
        migrations.AddField(
            model_name="nozzle",
            name="fuel_numeral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nozzles",
                to="sucursalApp.machinefuelinventorynumeral",
                verbose_name="Numeral",
            ),
        ),
    ]
