# Generated by Django 5.1.2 on 2025-12-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0032_remove_nozzle_fuel_inventory_nozzle_fuel_numeral"),
    ]

    operations = [
        migrations.AddField(
            model_name="nozzle",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Código enviado por la pistola para vincular lecturas IoT.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Código IoT",
            ),
        ),
    ]
