# Generated by Django 5.1.2 on 2025-12-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0033_nozzle_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinefuelinventorynumeral",
            name="numeral",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=12, verbose_name="Numeral"
            ),
        ),
    ]
