# Generated by Django 5.1.2 on 2025-12-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0034_alter_machinefuelinventorynumeral_numeral"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesession",
            name="close_mode",
            field=models.CharField(
                choices=[("numeral", "Modo numeral"), ("pistola", "Modo pistola")],
                default="numeral",
                max_length=20,
                verbose_name="Modo de cierre",
            ),
        ),
    ]
