# Generated by Django 5.1.2 on 2025-12-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0035_servicesession_close_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="number",
            field=models.PositiveIntegerField(verbose_name="Identificador de máquina"),
        ),
    ]
