# Generated by Django 5.1.2 on 2025-12-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0036_alter_machine_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesession",
            name="fuel_sales",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                verbose_name="Ventas de combustible (L)",
            ),
        ),
    ]
