# Generated by Django 5.1.2 on 2025-12-13 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0037_servicesession_fuel_sales"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSessionFuelSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        max_length=100, verbose_name="Tipo de combustible"
                    ),
                ),
                (
                    "liters_sold",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Litros vendidos",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "service_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_sales_by_type",
                        to="sucursalApp.servicesession",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta de combustible",
                "verbose_name_plural": "Ventas de combustible",
                "ordering": ("-created_at", "fuel_type"),
                "unique_together": {("service_session", "fuel_type")},
            },
        ),
    ]
