# Generated by Django 5.1.2 on 2025-12-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0038_servicesessionfuelsale"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesession",
            name="attendants_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Copia de los bomberos asignados al inicio del servicio.",
                verbose_name="Personal asignado (copia)",
            ),
        ),
    ]
