# Generated by Django 5.1.2 on 2025-12-14 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0041_alter_machine_fuel_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesession",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_sessions",
                to="sucursalApp.shift",
                verbose_name="Turno",
            ),
        ),
        migrations.AlterField(
            model_name="servicesessioncreditsale",
            name="fuel_inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_sales",
                to="sucursalApp.fuelinventory",
                verbose_name="Estanque",
            ),
        ),
        migrations.AlterField(
            model_name="servicesessionproductsaleitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_items",
                to="sucursalApp.branchproduct",
                verbose_name="Producto",
            ),
        ),
    ]
