# Generated by Django 5.1.2 on 2025-12-14 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0042_alter_servicesession_shift_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="fuel_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machines",
                to="sucursalApp.fuelinventory",
                verbose_name="Estanque principal",
            ),
        ),
    ]
