# Generated by Django 5.1.2 on 2025-12-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursalApp", "0043_alter_machine_fuel_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nozzle",
            name="fuel_numeral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nozzles",
                to="sucursalApp.machinefuelinventorynumeral",
                verbose_name="Numeral",
            ),
        ),
        migrations.AlterField(
            model_name="servicesessioncreditsale",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Número de factura"
            ),
        ),
    ]
